-- NEED POSTGIS extension enabled first

DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  password TEXT NOT NULL,
  bio VARCHAR(255) NOT NULL,
  -- location GEOGRAPHY(POINT)
  is_admin BOOLEAN DEFAULT FALSE,
  contact_info VARCHAR(20)
);
