DROP TABLE IF EXISTS map CASCADE;

CREATE TABLE map (
  id SERIAL PRIMARY KEY NOT NULL,
  sale_id INTEGER REFERENCES sales(id) ON DELETE CASCADE,
  event_id INTEGER REFERENCES events(event_id) ON DELETE CASCADE,
  location GEOGRAPHY(POINT) NOT NULL,
  address TEXT
);
