DROP TABLE IF EXISTS favourites CASCADE;

CREATE TABLE favourites  (
  id SERIAL PRIMARY KEY NOT NULL,
  consumer_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  sale_id INTEGER REFERENCES sales(id) ON DELETE CASCADE
);